In [1]:
import pandas as pd
from sklearn.model_selection import GridSearchCV , train_test_split 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report 
from sklearn.preprocessing import OneHotEncoder , OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [2]:
df=pd.read_csv("loan_data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

In [3]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [4]:
x=df.drop(columns='loan_status')
y=df.loan_status

In [5]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

In [6]:
num_cols = x.select_dtypes(include='number').columns
obj_cols= x.select_dtypes(include='object').columns

In [7]:
x[obj_cols].nunique()

person_gender                     2
person_education                  5
person_home_ownership             4
loan_intent                       6
previous_loan_defaults_on_file    2
dtype: int64

In [8]:
x['person_education'].unique()

array(['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate'],
      dtype=object)

In [9]:
order=(' Master','High School','Bachelor','Associate','Doctorate')

In [30]:
preprocessing = ColumnTransformer(
    transformers=[
        ('oneHot_encoder', OneHotEncoder(handle_unknown='ignore'),obj_cols.drop('person_education')),
        ('ordinal_encoder',OrdinalEncoder(categories=[order],handle_unknown='use_encoded_value',unknown_value=-1),['person_education'])

    ],remainder='passthrough'
)

main_pipeline = Pipeline(
    steps=[
        ('preprocessing',preprocessing),
        ('model', DecisionTreeClassifier(random_state=42))
    ]
)
grid_search_cv = GridSearchCV(
    estimator=main_pipeline,
    param_grid={
        'model__criterion':['gini','entropy'],
        'model__max_depth':[None,5,10],
        'model__min_samples_split':[2,5],
        'model__min_samples_leaf':[1,3],
        'model__splitter':['best','random']
    } ,verbose =10,n_jobs=-1
)
grid_search_cv.fit(xtrain , ytrain)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\compose\_column_transformer.py:1651: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

GridSearchCV(estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('oneHot_encoder',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         Index(['person_gender', 'person_home_ownership', 'loan_intent',
       'previous_loan_defaults_on_file'],
      dtype='object')),
                                                                        ('ordinal_encoder',
                                                                         OrdinalEncoder(categories=[(' '
                                                                                                     'Master',
                                                                                                     'High '
                                                                                                     'Scho...
                                                                                                     'Associate',
                                                                                                     'Doctorate')],
                                                                                        handle_unknown='use_encoded_value',
                                                                                        unknown_value=-1),
                                                                         ['person_education'])])),
                                       ('model',
                                        DecisionTreeClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__criterion': ['gini', 'entropy'],
                         'model__max_depth': [None, 5, 10],
                         'model__min_samples_leaf': [1, 3],
                         'model__min_samples_split': [2, 5],
                         'model__splitter': ['best', 'random']},
             verbose=10)

In [20]:
grid_search_cv.best_estimator_

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('oneHot_encoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['person_gender', 'person_home_ownership', 'loan_intent',
       'previous_loan_defaults_on_file'],
      dtype='object')),
                                                 ('ordinal_encoder',
                                                  OrdinalEncoder(categories=[(' '
                                                                              'Master',
                                                                              'High '
                                                                              'School',
                                                                              'Bachelor',
                                                                              'Associate',
                                                                              'Doctorate')],
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['person_education'])])),
                ('model',
                 DecisionTreeClassifier(criterion='entropy', max_depth=10,
                                        random_state=42))])

In [21]:
grid_search_cv.best_params_

{'model__criterion': 'entropy',
 'model__max_depth': 10,
 'model__min_samples_leaf': 1,
 'model__min_samples_split': 2,
 'model__splitter': 'best'}

In [22]:
grid_search_cv.cv_results_

{'mean_fit_time': array([0.218188  , 0.11172085, 0.21290722, 0.08941426, 0.1913856 ,
        0.08753257, 0.19129176, 0.08468251, 0.10554581, 0.0633975 ,
        0.10707068, 0.06378617, 0.10638156, 0.06617885, 0.10939183,
        0.06296072, 0.14456534, 0.0729588 , 0.14360995, 0.07627525,
        0.14580455, 0.07474957, 0.14841175, 0.07140746, 0.22511864,
        0.09463243, 0.22018971, 0.09931488, 0.23127737, 0.09014072,
        0.22427278, 0.09153123, 0.122153  , 0.06687436, 0.11700892,
        0.06613526, 0.12384644, 0.0710371 , 0.11561675, 0.0638526 ,
        0.15837364, 0.07248678, 0.15713415, 0.07255926, 0.15281129,
        0.07119222, 0.15309892, 0.07222915]),
 'std_fit_time': array([0.00868262, 0.00734868, 0.00885035, 0.00220512, 0.00097971,
        0.0025586 , 0.00260004, 0.00144764, 0.00074858, 0.00138854,
        0.00216497, 0.00194698, 0.00127198, 0.00320316, 0.00442146,
        0.00111814, 0.00325104, 0.00224329, 0.0011377 , 0.00946266,
        0.00246176, 0.00524244, 0.0056639 , 0.00182098, 0.01043469,
        0.00327722, 0.00304318, 0.00920683, 0.00627442, 0.00676019,
        0.01361327, 0.00332126, 0.00977765, 0.00532689, 0.00658906,
        0.00438334, 0.00970789, 0.00515892, 0.00507165, 0.00126189,
        0.00904431, 0.00142475, 0.00959467, 0.00089152, 0.00177798,
        0.00117022, 0.00185388, 0.00317357]),
 'mean_score_time': array([0.01857295, 0.01758308, 0.01642418, 0.01425056, 0.01386209,
        0.01416793, 0.0142642 , 0.0147552 , 0.01371908, 0.01314759,
        0.01344395, 0.01349907, 0.01389933, 0.01409397, 0.01347246,
        0.01323614, 0.0145472 , 0.01395926, 0.0136271 , 0.01362653,
        0.01355257, 0.01340504, 0.01297832, 0.01431904, 0.01383867,
        0.01556721, 0.01483016, 0.01491466, 0.01626177, 0.01375513,
        0.01676006, 0.01394095, 0.01380334, 0.01538   , 0.01386299,
        0.01425996, 0.01439667, 0.01498437, 0.01479549, 0.01330724,
        0.01326451, 0.01394095, 0.01325836, 0.01323709, 0.01345024,
        0.01347318, 0.01345472, 0.01363859]),
 'std_score_time': array([0.00157606, 0.00277633, 0.00162404, 0.00038165, 0.00051532,
        0.00060426, 0.00060305, 0.00056015, 0.00023507, 0.00024483,
        0.00031631, 0.00017246, 0.00045169, 0.0003772 , 0.00034703,
        0.00030718, 0.0019233 , 0.00077002, 0.00026089, 0.00102387,
        0.00075798, 0.00067975, 0.00040211, 0.00246837, 0.00042022,
        0.00226048, 0.0016287 , 0.00180438, 0.0019696 , 0.000357  ,
        0.00260845, 0.00041176, 0.00109766, 0.00197045, 0.00081832,
        0.00179887, 0.0014534 , 0.00205816, 0.00164539, 0.00027501,
        0.00034585, 0.00078268, 0.00035447, 0.00033074, 0.00032804,
        0.0003269 , 0.00042724, 0.00037989]),
 'param_model__criterion': masked_array(data=['gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_model__max_depth': masked_array(data=[None, None, None, None, None, None, None, None, 5, 5,
                    5, 5, 5, 5, 5, 5, 10, 10, 10, 10, 10, 10, 10, 10, None,
                    None, None, None, None, None, None, None, 5, 5, 5, 5,
                    5, 5, 5, 5, 10, 10, 10, 10, 10, 10, 10, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_model__min_samples_leaf': masked_array(data=[1, 1, 1, 1, 3, 3, 3, 3, 1, 1, 1, 1, 3, 3, 3, 3, 1, 1,
                    1, 1, 3, 3, 3, 3, 1, 1, 1, 1, 3, 3, 3, 3, 1, 1, 1, 1,
                    3, 3, 3, 3, 1, 1, 1, 1, 3, 3, 3, 3],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_model__min_samples_split': masked_array(data=[2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2,
                    5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5,
                    2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_model__splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'random'}],
 'split0_test_score': array([0.89694444, 0.88833333, 0.89513889, 0.89222222, 0.89819444,
        0.89263889, 0.89819444, 0.89263889, 0.90986111, 0.87305556,
        0.90986111, 0.87305556, 0.90986111, 0.87305556, 0.90986111,
        0.87305556, 0.91652778, 0.90388889, 0.91638889, 0.90902778,
        0.91652778, 0.90291667, 0.91652778, 0.90291667, 0.90041667,
        0.88958333, 0.90152778, 0.89555556, 0.89986111, 0.89055556,
        0.89986111, 0.89055556, 0.91027778, 0.86861111, 0.91027778,
        0.86861111, 0.91027778, 0.86861111, 0.91027778, 0.86861111,
        0.91958333, 0.90611111, 0.91958333, 0.90597222, 0.91916667,
        0.90402778, 0.91916667, 0.90402778]),
 'split1_test_score': array([0.90097222, 0.88833333, 0.90180556, 0.89722222, 0.90333333,
        0.89333333, 0.90333333, 0.89333333, 0.91666667, 0.87236111,
        0.91666667, 0.87236111, 0.91666667, 0.87236111, 0.91666667,
        0.87236111, 0.92388889, 0.91361111, 0.92375   , 0.90763889,
        0.92402778, 0.91625   , 0.92402778, 0.91625   , 0.90611111,
        0.89013889, 0.90736111, 0.89305556, 0.90930556, 0.89722222,
        0.90930556, 0.89722222, 0.91708333, 0.87083333, 0.91708333,
        0.87083333, 0.91708333, 0.87083333, 0.91708333, 0.87083333,
        0.92611111, 0.91111111, 0.92583333, 0.91041667, 0.92638889,
        0.90888889, 0.92638889, 0.90888889]),
 'split2_test_score': array([0.89944444, 0.88277778, 0.9       , 0.89277778, 0.90694444,
        0.89291667, 0.90694444, 0.89291667, 0.90875   , 0.87166667,
        0.90875   , 0.87166667, 0.90875   , 0.87166667, 0.90875   ,
        0.87166667, 0.91486111, 0.89638889, 0.91444444, 0.90763889,
        0.91555556, 0.91069444, 0.91555556, 0.91069444, 0.89736111,
        0.89194444, 0.89875   , 0.8875    , 0.89888889, 0.89111111,
        0.89888889, 0.89111111, 0.90888889, 0.87166667, 0.90888889,
        0.87166667, 0.90888889, 0.87166667, 0.90888889, 0.87166667,
        0.91486111, 0.89958333, 0.91486111, 0.89944444, 0.91541667,
        0.90541667, 0.91541667, 0.90541667]),
 'split3_test_score': array([0.90125   , 0.89125   , 0.90166667, 0.89069444, 0.90111111,
        0.89263889, 0.90111111, 0.89263889, 0.91555556, 0.8725    ,
        0.91555556, 0.8725    , 0.91555556, 0.8725    , 0.91555556,
        0.8725    , 0.91930556, 0.89916667, 0.91972222, 0.90819444,
        0.91777778, 0.905     , 0.91777778, 0.905     , 0.89791667,
        0.88791667, 0.90041667, 0.89027778, 0.90152778, 0.89638889,
        0.90152778, 0.89638889, 0.91263889, 0.87708333, 0.91263889,
        0.87708333, 0.91263889, 0.87708333, 0.91263889, 0.87708333,
        0.92083333, 0.90125   , 0.92055556, 0.90777778, 0.92013889,
        0.90902778, 0.92013889, 0.90902778]),
 'split4_test_score': array([0.89569444, 0.89083333, 0.90125   , 0.89319444, 0.90263889,
        0.89541667, 0.90263889, 0.89541667, 0.915     , 0.87263889,
        0.915     , 0.87263889, 0.915     , 0.87263889, 0.915     ,
        0.87263889, 0.91916667, 0.90958333, 0.91930556, 0.90555556,
        0.92013889, 0.91180556, 0.92013889, 0.91180556, 0.89875   ,
        0.89597222, 0.90013889, 0.89777778, 0.89902778, 0.89527778,
        0.89902778, 0.89527778, 0.91486111, 0.87541667, 0.91486111,
        0.87541667, 0.91486111, 0.87541667, 0.91486111, 0.87541667,
        0.92055556, 0.90722222, 0.92069444, 0.90680556, 0.92      ,
        0.90166667, 0.92      , 0.90166667]),
 'mean_test_score': array([0.89886111, 0.88830556, 0.89997222, 0.89322222, 0.90244444,
        0.89338889, 0.90244444, 0.89338889, 0.91316667, 0.87244444,
        0.91316667, 0.87244444, 0.91316667, 0.87244444, 0.91316667,
        0.87244444, 0.91875   , 0.90452778, 0.91872222, 0.90761111,
        0.91880556, 0.90933333, 0.91880556, 0.90933333, 0.90011111,
        0.89111111, 0.90163889, 0.89283333, 0.90172222, 0.89411111,
        0.90172222, 0.89411111, 0.91275   , 0.87272222, 0.91275   ,
        0.87272222, 0.91275   , 0.87272222, 0.91275   , 0.87272222,
        0.92038889, 0.90505556, 0.92030556, 0.90608333, 0.92022222,
        0.90580556, 0.92022222, 0.90580556]),
 'std_test_score': array([0.00220024, 0.00302051, 0.00249907, 0.002172  , 0.00286071,
        0.00104527, 0.00286071, 0.00104527, 0.00321719, 0.00045304,
        0.00321719, 0.00045304, 0.00321719, 0.00045304, 0.00321719,
        0.00045304, 0.00306438, 0.00637898, 0.00317373, 0.00114665,
        0.00302841, 0.00481157, 0.00302841, 0.00481157, 0.00317251,
        0.00274986, 0.00299485, 0.0036574 , 0.00390631, 0.0027521 ,
        0.00390631, 0.0027521 , 0.00297547, 0.00309395, 0.00297547,
        0.00309395, 0.00297547, 0.00309395, 0.00297547, 0.00309395,
        0.00358258, 0.00416907, 0.00349095, 0.00364027, 0.00352964,
        0.00284013, 0.00352964, 0.00284013]),
 'rank_test_score': array([32, 40, 31, 37, 25, 35, 25, 35,  9, 45,  9, 45,  9, 45,  9, 45,  7,
        24,  8, 19,  5, 17,  5, 17, 30, 39, 29, 38, 27, 33, 27, 33, 13, 41,
        13, 41, 13, 41, 13, 41,  1, 23,  2, 20,  3, 21,  3, 21],
       dtype=int32)}

In [23]:
results = pd.DataFrame(grid_search_cv.cv_results_)

In [28]:
results.sort_values(by='rank_test_score').head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__criterion,param_model__max_depth,param_model__min_samples_leaf,param_model__min_samples_split,param_model__splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
40,0.158374,0.009044,0.013265,0.000346,entropy,10,1,2,best,"{'model__criterion': 'entropy', 'model__max_de...",0.919583,0.926111,0.914861,0.920833,0.920556,0.920389,0.003583,1
42,0.157134,0.009595,0.013258,0.000354,entropy,10,1,5,best,"{'model__criterion': 'entropy', 'model__max_de...",0.919583,0.925833,0.914861,0.920556,0.920694,0.920306,0.003491,2
46,0.153099,0.001854,0.013455,0.000427,entropy,10,3,5,best,"{'model__criterion': 'entropy', 'model__max_de...",0.919167,0.926389,0.915417,0.920139,0.920000,0.920222,0.003530,3
44,0.152811,0.001778,0.013450,0.000328,entropy,10,3,2,best,"{'model__criterion': 'entropy', 'model__max_de...",0.919167,0.926389,0.915417,0.920139,0.920000,0.920222,0.003530,3
20,0.145805,0.002462,0.013553,0.000758,gini,10,3,2,best,"{'model__criterion': 'gini', 'model__max_depth...",0.916528,0.924028,0.915556,0.917778,0.920139,0.918806,0.003028,5

In [ ]:
#try grid seach cv for logistic regression and random forest- assignment